name: Java CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - loader: fabric
            project: fabric
            java-version: 17

          - loader: forge
            project: forge
            java-version: 17

          - loader: forge
            project: forge-legacy
            java-version: 8

          - loader: neoforge
            project: neoforge
            java-version: 21

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
    - name: Build ${{ matrix.loader }}
      run: ./gradlew :${{ matrix.project }}:build
    - name: Upload Artifact - ${{ matrix.loader }}
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: imblocker-${{ matrix.loader }}
        # Directory containing files to upload
        path: ${{ matrix.project }}/build/libs/*.jar
